export const THEME = "THEME";
export const GETTOKEN = "GETTOKEN";
export const UPDATELIKES = "UPDATELIKES";
export const UPDATE_SINGLE_PHOTO_STATE = "UPDATE_SINGLE_PHOTO_STATE";
export const ISMOUNTED = "ISMOUNTED";
export const TOGGLE_THEME = "TOGGLE_THEME";
export const UPDATE_COLLECTION_STATE = "UPDATE_COLLECTION_STATE";
export const GO_TO_HOME = "GO_TO_HOME";

//TYPES WITH FETCH REQUEST

//GET COLLECTION
export const COLLECTION_REQUEST = "COLLECTION_REQUEST";
export const COLLECTION_REQUEST_SUCCESS = "COLLECTION_REQUEST_SUCCESS";
export const COLLECTION_REQUEST_ERROR = "COLLECTION_REQUEST_ERROR";

//GET PHOTOS LIST
export const PHOTOS_REQUEST = "PHOTOS_REQUEST";
export const PHOTOS_REQUEST_SUCCESS = "PHOTOS_REQUEST_SUCCESS";
export const PHOTOS_REQUEST_ERROR = "PHOTOS_REQUEST_ERROR";

//GET DATA FOR AUTHORIZATION
export const ME_REQUEST = "ME_REQUEST";
export const ME_REQUEST_SUCCESS = "ME_REQUEST_SUCCESS";
export const ME_REQUEST_ERROR = "ME_REQUEST_ERROR";

//GET LIKE
export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_REQUEST_SUCCESS = "LIKE_REQUEST_SUCCESS";
export const LIKE_REQUEST_ERROR = "LIKE_REQUEST_ERROR";

//MODAL GET PHOTO
export const SINGLE_PHOTO_REQUEST = "SINGLE_PHOTO_REQUEST";
export const SINGLE_PHOTO_REQUEST_SUCCESS = "SINGLE_PHOTO_REQUEST_SUCCESS";
export const SINGLE_PHOTO_REQUEST_ERROR = "SINGLE_PHOTO_REQUEST_ERROR";
